### ISSUE TITLE
Yahoo have changed their API and the library no longer works

### ISSUE THREAD

**Issue by PeterSumm** [gregoiresage/fitbit-weather#10]
Yahoo changed their API on Jan 3 and broke your library.

Are you aware of this and planning to fix it, or should I find my own solution?

Thanks,

Peter

**Comment by gregoiresage** [comment]
Hi,

If Yahoo doesn't provide a weather API anymore, you can still one of the
other supported providers

Le jeu. 10 janv. 2019 à 08:36, PeterSumm <notifications@github.com> a
écrit :

**Comment by PeterSumm** [comment]
OK, thanks.

**Comment by gregoiresage** [comment]
I've removed yahoo support
