### ISSUE TITLE
On device weather does not update

### ISSUE THREAD

**Issue by florinstefan** [gregoiresage/fitbit-weather#13]
on the device the weather is not working, although it is working on the simulator.

**Comment by geoffhuntsgood** [comment]
Can you give some more detail and/or a code sample? I have weather showing up properly on my Versa 2.

**Comment by ghost** [comment]
I do have the same issue from time to time on my watch faces. Although i am using an altered version to my needs, I could track down the problem to the geolocation call. 
Sometimes the companion cannot get a geolocation position, so the call to geolocation.getCurrentPosition blocks for an infinite time. When the location can be determined all promises get resolved. To fix that the call to geolocation.getCurrentPosition should include the timeout option as described in the ref:
https://dev.fitbit.com/build/reference/device-api/geolocation/
