### ISSUE TITLE
Weather error No connection with the companion

### ISSUE THREAD

**Issue by parkour86** [gregoiresage/fitbit-weather#6]
I followed the Readme and keep receiving the error "Weather error No connection with the companion". I think i'm missing something. I tried wunderground and darksky APIs. Please advice on what to do next.

**Comment by gregoiresage** [comment]
have you checked the location and internet permissions ?

2018-04-18 3:59 GMT+02:00 parkour86 <notifications@github.com>:

**Comment by gregoiresage** [comment]
Let's say it is resolved :-)
