### ISSUE TITLE
Clock face

### ISSUE THREAD

**Issue by skipgoldberg** [gregoiresage/fitbit-weather#9]
Hi, love app but would love to see new version to allow custom face color change option as well as background color change options!
It would make it much more fun !!!
Thanks. 
Skip

**Comment by gregoiresage** [comment]
This is not a clockface, it's just a library for weather integration in clockfaces... I'm not sure what I need to do for you

**Comment by skipgoldberg** [comment]
What. I am asking is this.
Can you Add custom colours
To app?
Change clock Colors.    Also background colors.   


Skip

**Comment by gregoiresage** [comment]
Sorry I don't get it... Which app are you talking about ? The demo app of this repo ? It is just an app to show how to integrate the library, nothing more

**Comment by skipgoldberg** [comment]
Fit bit app
  Time date weather 

Skip

**Comment by gregoiresage** [comment]
mmm that's not one of my clockface :-p

**Comment by rob-migz** [comment]
Hi Gregoire, I recently added the Colfaxness clock face to my Fitbit Versa. However, the weather is not showing up. I’m in Fredericton, New Brunswick, Canada. Please help!

Thank you

**Comment by gregoiresage** [comment]
You should contact the developer of the clockface directly, I don't know
how he integrated the library.

**Comment by skipgoldberg** [comment]
Why you sent this to me dumb fuck
